Skip to content
Navigation Menu
kinanmjeed88
kinantouch

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Deploy Vite site to GitHub Pages
Delete .github/workflows/pages.yml #22
Jobs
Run details
Annotations
1 error
build
failed 1 minute ago in 27s
Search logs
2s
0s
3s
14s
6s
Run npm run build

> techtouch-hub@1.0.0 build
> tsc && vite build

vite v5.4.21 building for production...
transforming...
âœ“ 1589 modules transformed.
x Build failed in 2.77s
error during build:
[vite:terser] terser not found. Since Vite v3, terser has become an optional dependency. You need to install it.
    at loadTerserPath (file:///home/runner/work/kinantouch/kinantouch/node_modules/vite/dist/node/chunks/dep-BK3b2jBa.js:19705:13)
    at Object.renderChunk (file:///home/runner/work/kinantouch/kinantouch/node_modules/vite/dist/node/chunks/dep-BK3b2jBa.js:19740:27)
    at file:///home/runner/work/kinantouch/kinantouch/node_modules/rollup/dist/es/shared/node-entry.js:22494:40
Error: Process completed with exit code 1.
0s
0s
0s
0s
